default:
    @just format
    @just test
    @just build

format:
    cargo fmt

clean:
    git clean -fdx -e .env

build:
    cargo build --release --target wasm32-unknown-unknown
    wasm-bindgen target/wasm32-unknown-unknown/release/wasm.wasm --out-dir build --target web

test:
    cargo test
